### ISSUE TITLE
Broken documentation storybook

### ISSUE THREAD

**Issue by GeorgeWL** [morewings/cra-template-npm-library#611]
Due to an error in storybook, all of the views in the storybook documentation at https://cra-template-npm-library.netlify.com/ are showing as blank pages with no contents

```js
vendors~main.d00ba054.iframe.bundle.js:2 Uncaught (in promise) Error: No `docs.container` set, did you run `addon-docs/preset`?
    at StoryRenderer.renderDocs (vendors~main.d00ba054.iframe.bundle.js:2:1116962)
    at StoryRenderer._callee2$ (vendors~main.d00ba054.iframe.bundle.js:2:1112281)
    at tryCatch (vendors~main.d00ba054.iframe.bundle.js:2:355135)
    at Generator.invoke [as _invoke] (vendors~main.d00ba054.iframe.bundle.js:2:354758)
    at Generator.next (vendors~main.d00ba054.iframe.bundle.js:2:355901)
    at StoryRenderer_asyncGeneratorStep (vendors~main.d00ba054.iframe.bundle.js:2:1105784)
    at _next (vendors~main.d00ba054.iframe.bundle.js:2:1106099)
    at vendors~main.d00ba054.iframe.bundle.js:2:1106277
    at new Promise (<anonymous>)
    at StoryRenderer.<anonymous> (vendors~main.d00ba054.iframe.bundle.js:2:1106011)
```
![broken storybooks](https://user-images.githubusercontent.com/5931248/154679948-847baaf7-0fa2-410e-967f-ede11586a63b.gif)

**Comment by morewings** [comment]
Should be fixed now. Thanks for reporting @GeorgeWL
